# Action Cable uses Redis by default to administer connections, channels, and sending/receiving messages over the WebSocket.
local: &local
  adapter: redis
  url: redis://localhost:7777/0

production: *local
development:  *local
test: *local
