#
# Provides a config for Redic to connect to a redis-instance
#
# Will be used by ohm-initializer to construct an url in the form of:
#
# redis://:<passwd>@<host>:<port>/<database>
#
default: &default
  host: localhost
  port: 7777

production:
  <<: *default
  database: 0

development:
  <<: *default
  database: 1

test: &test
  <<: *default
  database: <%= 2 + (ENV['TEST_ENV_NUMBER'] || 0) %>
